{
 "title": "Geiger Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Geiger Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "query": "SELECT \"latitude\" as lat, \"longitude\" as lon,\"cpm\" as cpm, \"cpm_level\" as cpm_level, \"display\" as display,  \"time\" as date, \"satellites\" as satellites, \"elevation\" as elevation, \"dist_initial\" as dist_initial, \"dist_last\" as dist_last , \"time\" as time_index FROM \"GPSCPM\"  WHERE $timeFilter AND display = 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "GeigerUnit", "operator": "=", "value": "CPM" }
     ]
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "satellites",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "select": [
      [
       { "params": [ "satellites" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "GeigerUnit", "operator": "=", "value": "CPM" }
     ]
    }
   ]
  },
  {
   "title": "CPM Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "select": [
      [
       { "params": [ "cpm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elevation (m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "elevation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "select": [
      [
       { "params": [ "elevation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "GeigerUnit", "operator": "=", "value": "CPM" }
     ]
    }
   ]
  },
  {
   "title": "μSv",
   "type": "timeseries",
   "description": "These values are to be taken with a grain of salt.\nThe GMC-500 is pre configured with the factor 0.00833333333",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "μSv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "query": "SELECT last(\"cpm\") *(0.5/60) FROM \"GPSCPM\" WHERE (\"GeigerUnit\" = 'CPM') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(0.5/60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "GeigerUnit", "operator": "=", "value": "CPM" }
     ]
    }
   ]
  },
  {
   "title": "CPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "cpm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPSCPM",
     "select": [
      [
       { "params": [ "cpm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "GeigerUnit", "operator": "=", "value": "CPM" }
     ]
    }
   ]
  }
 ]
}